dist: xenial
services:
- postgresql
addons:
  postgresql: '9.4'
before_script:
- psql -U postgres -c "create user decide password 'decide'"
- psql -U postgres -c "create database test_decide2 owner decide"
- psql -U postgres -c "ALTER USER decide CREATEDB"
language: python
python:
- '3.6'
<<<<<<< HEAD
branches:
  only:
  - master
=======
>>>>>>> desarrollo
install:
- pip install -r requirements.txt
script:
- cd decide
<<<<<<< HEAD
- python ./manage.py test --keepdb
=======
- python ./manage.py test store --keepdb
>>>>>>> desarrollo
